### ISSUE TITLE
Application for 17lwinn

### ISSUE THREAD

**Issue by 17lwinn** [Code4Covid/Staff-Applications#1]
Hi!

I am wishing to help with this, I am a developer at Scripting To Save Lives and want to help with some stuff!

I can do bash, python, html. But mainly python.

**Comment by rockstarrudy** [comment]
Well @aboutDavid said that the site is using .md no html @17lwinn

**Comment by rockstarrudy** [comment]
@17lwinn let me ping @aboutDavid beacuse I dont have perms

**Comment by 17lwinn** [comment]
okay, i can do python mainly- plus markdown aswell.

Python: can write a CLI with argparse
MD: write docs (more of a coder really tbh)

**Comment by rockstarrudy** [comment]
@17lwinn you have been accepted !

**Comment by 17lwinn** [comment]
thank you very much! where shall I begin @codersuntited @aboutDavid ?

**Comment by dispherical** [comment]
> thank you very much! where shall I begin @codersuntited @aboutDavid ?

I sent you a owner invite to the organization.

**Comment by 17lwinn** [comment]
okay thank you, i'll check now

**Comment by 17lwinn** [comment]
okay, i have joined!

**Comment by dispherical** [comment]
:D
