### ISSUE TITLE
Application for codersunited (will reopen about 1 week)

### ISSUE THREAD

**Issue by rockstarrudy** [Code4Covid/Staff-Applications#4]
@aboutDavid can I be a application manager?

_Originally posted by @codersuntited in https://github.com/Code4Covid/Staff-Applications/issues/2#issuecomment-683948190_

can I? @17lwinn ?

**Comment by dispherical** [comment]
> @aboutDavid can I be a application manager?
> 
> _Originally posted by @codersuntited in [#2 (comment)](https://github.com/Code4Covid/Staff-Applications/issues/2#issuecomment-683948190)_
> 
> can I? @17lwinn ?

Sure, I'll add you to the team.

**Comment by rockstarrudy** [comment]
thx @aboutDavid

**Comment by rockstarrudy** [comment]
tell me when you add me @aboutDavid

**Comment by rockstarrudy** [comment]
@aboutDavid can I have owner perms for the org? So I can invite people to the repo if they pass the applications and I can make the template a real template

**Comment by rockstarrudy** [comment]
@aboutDavid are you online?

**Comment by rockstarrudy** [comment]
@aboutDavid why dont I have perms in this repo even tho I am applications manager

**Comment by dispherical** [comment]
Actually, right now, I'm going to have to reject this because we already have like 3 Application managers, I'll reopen them in about a week.

**Comment by rockstarrudy** [comment]
@aboutDavid who are they?

**Comment by rockstarrudy** [comment]
@aboutDavid is there anything else I can apply for?

**Comment by rockstarrudy** [comment]
@aboutDavid also how is the forum?

**Comment by dispherical** [comment]
> @aboutDavid also how is the forum?

It's setup, you can create an account now.
@codersuntited
